<?php

/**
 * @file
 * Contains modulo_teste.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function modulo_teste_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the modulo_teste module.
    case 'help.page.modulo_teste':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function modulo_teste_theme() {
  var_dump("boa noiteee");
  return [
    'modulo_teste' => [
      'variables' => ['data' => NULL],
      // 'render element' => 'children',
    ],
  ];
}
